Fix: tsc did not build
cli/run/loadConfigFile.ts:114:4 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

114    defaultLoader(module, requiredFileName);
       ~~~~~~~~~~~~~